--[[
    Auto-Generated Roblox Script Hub UI
    Generated by: generate_hub.py
    Admin Key: käsigerniklas
    Games Loaded: 3
    
    Place this as a LocalScript in StarterGui
]]

local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

-- Config
local CONFIG = {
    AdminKey = "käsigerniklas",
    HubTitle = "Script Hub",
    Subtitle = "Auto-Loaded Scripts",
    Theme = {
        Background = Color3.fromRGB(15, 15, 20),
        CardBackground = Color3.fromRGB(25, 25, 35),
        Primary = Color3.fromRGB(139, 92, 246),
        Secondary = Color3.fromRGB(236, 72, 153),
        Accent = Color3.fromRGB(59, 130, 246),
        Text = Color3.fromRGB(255, 255, 255),
        TextDim = Color3.fromRGB(180, 180, 190),
        Error = Color3.fromRGB(239, 68, 68),
        Success = Color3.fromRGB(34, 197, 94),
        Border = Color3.fromRGB(60, 60, 80)
    }
}

local GAMES = {
    {
        id = "adoptme",
        name = "Adopt Me",
        icon = "rbxassetid://126515219349576",
        description = "Auto-Farm Pattern Detection",
        color = Color3.fromRGB(236, 72, 153),
        script = function()
            -- @name: Adopt Me
            -- @description: Auto-Farm Pattern Detection
            -- @color: 236, 72, 153
            -- @icon: rbxassetid://126515219349576
            
            print("[AdoptMe] Initializing anticheat test module...")
            
            -- Simulate auto-farm repetitive behavior
            local function testAutoFarmDetection()
                print("[AdoptMe] Simulating repetitive action pattern (auto-farm)...")
                
                local actionCount = 0
                local startTime = tick()
                
                -- Simulate rapid repetitive actions
                for i = 1, 20 do
                    actionCount += 1
                    
                    -- Simulate different action types
                    local actions = {"Click", "Collect", "Feed", "Play"}
                    local action = actions[(i % #actions) + 1]
                    
                    print("[AdoptMe] Action " .. actionCount .. ": " .. action)
                    task.wait(0.3) -- Fast repetitive pattern
                end
                
                local elapsed = tick() - startTime
                print("[AdoptMe] Pattern analysis: " .. actionCount .. " actions in " .. string.format("%.1f", elapsed) .. " seconds")
                
                -- Flag if actions are too fast
                if actionCount / elapsed > 3 then
                    warn("[AdoptMe] DETECTED: High frequency action pattern (possible auto-farm)")
                end
            end
            
            -- Simulate bot-like movement
            local function testBotMovement()
                print("[AdoptMe] Testing bot movement detection...")
                
                local player = game.Players.LocalPlayer
                local character = player.Character
                if not character then return end
                
                local hrp = character:FindFirstChild("HumanoidRootPart")
                if not hrp then return end
                
                -- Simulate perfectly linear movement (bot-like)
                local startPos = hrp.Position
                local direction = Vector3.new(1, 0, 0)
                
                for i = 1, 5 do
                    local targetPos = startPos + (direction * i * 10)
                    hrp.CFrame = CFrame.new(targetPos)
                    print("[AdoptMe] Teleported to: " .. tostring(targetPos))
                    task.wait(0.5)
                end
                
                -- Return to start
                hrp.CFrame = CFrame.new(startPos)
                print("[AdoptMe] Returned to start position")
            end
            
            -- Run tests
            print("[AdoptMe] Starting test sequence...")
            testAutoFarmDetection()
            task.wait(1)
            testBotMovement()
            print("[AdoptMe] All tests completed successfully")
        end
    },
    {
        id = "bloxfruits",
        name = "Blox Fruits",
        icon = "rbxassetid://126515219349576",
        description = "Speed & Fly Detection Test",
        color = Color3.fromRGB(239, 68, 68),
        script = function()
            -- @name: Blox Fruits
            -- @description: Speed & Fly Detection Test
            -- @color: 239, 68, 68
            -- @icon: rbxassetid://126515219349576
            
            print("[BloxFruits] Initializing anticheat test module...")
            
            -- Simulate speed detection
            local function testSpeedDetection()
                local player = game.Players.LocalPlayer
                local character = player.Character
                if not character then
                    warn("[BloxFruits] Character not found, waiting...")
                    return
                end
                
                local humanoid = character:FindFirstChild("Humanoid")
                if not humanoid then
                    warn("[BloxFruits] Humanoid not found")
                    return
                end
                
                local normalSpeed = humanoid.WalkSpeed
                print("[BloxFruits] Normal speed detected: " .. normalSpeed)
                
                -- Simulate speed hack
                warn("[BloxFruits] Simulating speed modification...")
                humanoid.WalkSpeed = 100
                task.wait(1)
                
                -- Reset to normal
                humanoid.WalkSpeed = normalSpeed
                print("[BloxFruits] Speed restored to: " .. normalSpeed)
            end
            
            -- Simulate fly detection
            local function testFlyDetection()
                print("[BloxFruits] Testing fly detection...")
                local player = game.Players.LocalPlayer
                local character = player.Character
                if not character then return end
                
                local humanoid = character:FindFirstChild("Humanoid")
                if not humanoid then return end
                
                -- Enable PlatformStand (simulates flying/no-clip state)
                humanoid.PlatformStand = true
                warn("[BloxFruits] PlatformStand enabled (fly state)")
                task.wait(2)
                
                humanoid.PlatformStand = false
                print("[BloxFruits] PlatformStand disabled")
            end
            
            -- Run tests
            print("[BloxFruits] Starting test sequence...")
            testSpeedDetection()
            task.wait(1)
            testFlyDetection()
            print("[BloxFruits] All tests completed successfully")
        end
    },
    {
        id = "jailbreak",
        name = "Jailbreak",
        icon = "rbxassetid://126515219349576",
        description = "Teleport & Noclip Detection",
        color = Color3.fromRGB(59, 130, 246),
        script = function()
            -- @name: Jailbreak
            -- @description: Teleport & Noclip Detection
            -- @color: 59, 130, 246
            -- @icon: rbxassetid://126515219349576
            
            print("[Jailbreak] Initializing anticheat test module...")
            
            -- Simulate teleport detection
            local function testTeleportDetection()
                print("[Jailbreak] Testing teleport detection...")
                
                local player = game.Players.LocalPlayer
                local character = player.Character
                if not character then
                    warn("[Jailbreak] Character not found")
                    return
                end
                
                local hrp = character:FindFirstChild("HumanoidRootPart")
                if not hrp then
                    warn("[Jailbreak] HumanoidRootPart not found")
                    return
                end
                
                -- Record original position
                local originalCFrame = hrp.CFrame
                local originalPos = hrp.Position
                print("[Jailbreak] Original position: " .. tostring(originalPos))
                
                -- Simulate sudden large teleport (500 studs)
                local teleportOffset = Vector3.new(500, 0, 0)
                local newPos = originalPos + teleportOffset
                
                warn("[Jailbreak] Simulating teleport: 500 studs")
                hrp.CFrame = CFrame.new(newPos)
                print("[Jailbreak] New position: " .. tostring(newPos))
                
                task.wait(1)
                
                -- Check if anticheat would detect this
                local distance = (hrp.Position - originalPos).Magnitude
                if distance > 50 then
                    warn("[Jailbreak] DETECTED: Large position change (" .. string.format("%.0f", distance) .. " studs)")
                end
                
                -- Restore position
                hrp.CFrame = originalCFrame
                print("[Jailbreak] Position restored")
            end
            
            -- Simulate noclip detection
            local function testNoclipDetection()
                print("[Jailbreak] Testing noclip detection...")
                
                local player = game.Players.LocalPlayer
                local character = player.Character
                if not character then return end
                
                local originalStates = {}
                
                -- Disable collision on all character parts
                for _, part in ipairs(character:GetDescendants()) do
                    if part:IsA("BasePart") then
                        originalStates[part] = part.CanCollide
                        part.CanCollide = false
                        print("[Jailbreak] Disabled collision: " .. part.Name)
                    end
                end
                
                warn("[Jailbreak] Noclip state enabled")
                task.wait(2)
                
                -- Restore collision
                for part, state in pairs(originalStates) do
                    part.CanCollide = state
                end
                
                print("[Jailbreak] Collision restored on all parts")
            end
            
            -- Simulate vehicle speed hack
            local function testVehicleSpeed()
                print("[Jailbreak] Testing vehicle speed detection...")
                
                -- Look for vehicle in workspace
                local player = game.Players.LocalPlayer
                local character = player.Character
                if not character then return end
                
                -- Check if sitting in vehicle
                local humanoid = character:FindFirstChild("Humanoid")
                if humanoid and humanoid.SeatPart then
                    local vehicle = humanoid.SeatPart.Parent
                    if vehicle then
                        local bodyVelocity = vehicle:FindFirstChild("BodyVelocity")
                        if bodyVelocity then
                            local originalVelocity = bodyVelocity.Velocity
                            bodyVelocity.Velocity = Vector3.new(1000, 0, 0)
                            warn("[Jailbreak] Simulating vehicle speed hack")
                            task.wait(1)
                            bodyVelocity.Velocity = originalVelocity
                            print("[Jailbreak] Vehicle velocity restored")
                        end
                    end
                else
                    print("[Jailbreak] Not in vehicle, skipping vehicle test")
                end
            end
            
            -- Run tests
            print("[Jailbreak] Starting test sequence...")
            testTeleportDetection()
            task.wait(1)
            testNoclipDetection()
            task.wait(1)
            testVehicleSpeed()
            print("[Jailbreak] All tests completed successfully")
        end
    }
}

-- Helpers
local function corner(parent, r)
    local c = Instance.new("UICorner")
    c.CornerRadius = UDim.new(0, r or 8)
    c.Parent = parent
end

local function stroke(parent, col, thick)
    local s = Instance.new("UIStroke")
    s.Color = col or CONFIG.Theme.Border
    s.Thickness = thick or 1
    s.Parent = parent
end

local function tween(obj, props, dur, style, dir)
    TweenService:Create(obj, TweenInfo.new(dur or 0.3, style or Enum.EasingStyle.Quad, dir or Enum.EasingDirection.Out), props):Play()
end

-- Main UI
local sg = Instance.new("ScreenGui")
sg.Name = "AutoScriptHub"
sg.ResetOnSpawn = false
sg.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
sg.Parent = playerGui

local main = Instance.new("Frame")
main.Size = UDim2.new(0, 500, 0, 400)
main.Position = UDim2.new(0.5, -250, 0.5, -200)
main.BackgroundColor3 = CONFIG.Theme.Background
main.BorderSizePixel = 0
main.Parent = sg

corner(main, 16)
stroke(main, CONFIG.Theme.Border, 1)

-- Shadow
local sh = Instance.new("ImageLabel")
sh.AnchorPoint = Vector2.new(0.5, 0.5)
sh.Position = UDim2.new(0.5, 0, 0.5, 4)
sh.Size = UDim2.new(1, 40, 1, 40)
sh.BackgroundTransparency = 1
sh.Image = "rbxassetid://1316045217"
sh.ImageColor3 = Color3.fromRGB(0, 0, 0)
sh.ImageTransparency = 0.6
sh.ScaleType = Enum.ScaleType.Slice
sh.SliceCenter = Rect.new(10, 10, 118, 118)
sh.ZIndex = -1
sh.Parent = main

-- ===== KEY SCREEN =====
local keyFrame = Instance.new("Frame")
keyFrame.Size = UDim2.new(1, 0, 1, 0)
keyFrame.BackgroundTransparency = 1
keyFrame.Parent = main

local iconBox = Instance.new("Frame")
iconBox.Size = UDim2.new(0, 64, 0, 64)
iconBox.Position = UDim2.new(0.5, -32, 0, 40)
iconBox.BackgroundColor3 = CONFIG.Theme.Primary
iconBox.Parent = keyFrame

corner(iconBox, 16)

local iconTxt = Instance.new("TextLabel")
iconTxt.Size = UDim2.new(1, 0, 1, 0)
iconTxt.BackgroundTransparency = 1
iconTxt.Text = "🛡️"
iconTxt.TextSize = 32
iconTxt.Font = Enum.Font.GothamBold
iconTxt.Parent = iconBox

local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, -40, 0, 30)
title.Position = UDim2.new(0, 20, 0, 120)
title.BackgroundTransparency = 1
title.Text = CONFIG.HubTitle
title.TextColor3 = CONFIG.Theme.Text
title.TextSize = 24
title.Font = Enum.Font.GothamBold
title.TextXAlignment = Enum.TextXAlignment.Center
title.Parent = keyFrame

local sub = Instance.new("TextLabel")
sub.Size = UDim2.new(1, -40, 0, 20)
sub.Position = UDim2.new(0, 20, 0, 152)
sub.BackgroundTransparency = 1
sub.Text = CONFIG.Subtitle
sub.TextColor3 = CONFIG.Theme.TextDim
sub.TextSize = 14
sub.Font = Enum.Font.Gotham
sub.TextXAlignment = Enum.TextXAlignment.Center
sub.Parent = keyFrame

local keyBox = Instance.new("TextBox")
keyBox.Size = UDim2.new(1, -80, 0, 44)
keyBox.Position = UDim2.new(0, 40, 0, 200)
keyBox.BackgroundColor3 = CONFIG.Theme.CardBackground
keyBox.BorderSizePixel = 0
keyBox.Text = ""
keyBox.PlaceholderText = "Enter access key..."
keyBox.TextColor3 = CONFIG.Theme.Text
keyBox.PlaceholderColor3 = CONFIG.Theme.TextDim
keyBox.TextSize = 14
keyBox.Font = Enum.Font.Gotham
keyBox.ClearTextOnFocus = false
keyBox.Parent = keyFrame

corner(keyBox, 10)
stroke(keyBox, CONFIG.Theme.Border, 1)

local submit = Instance.new("TextButton")
submit.Size = UDim2.new(1, -80, 0, 44)
submit.Position = UDim2.new(0, 40, 0, 260)
submit.BackgroundColor3 = CONFIG.Theme.Primary
submit.BorderSizePixel = 0
submit.Text = "Authenticate"
submit.TextColor3 = CONFIG.Theme.Text
submit.TextSize = 14
submit.Font = Enum.Font.GothamBold
submit.AutoButtonColor = false
submit.Parent = keyFrame

corner(submit, 10)

local errLabel = Instance.new("TextLabel")
errLabel.Size = UDim2.new(1, -80, 0, 30)
errLabel.Position = UDim2.new(0, 40, 0, 316)
errLabel.BackgroundTransparency = 1
errLabel.Text = ""
errLabel.TextColor3 = CONFIG.Theme.Error
errLabel.TextSize = 12
errLabel.Font = Enum.Font.Gotham
errLabel.TextXAlignment = Enum.TextXAlignment.Center
errLabel.Parent = keyFrame

local status = Instance.new("TextLabel")
status.Size = UDim2.new(1, -40, 0, 20)
status.Position = UDim2.new(0, 20, 1, -40)
status.BackgroundTransparency = 1
status.Text = tostring(#GAMES) .. " scripts loaded | Sandbox Environment"
status.TextColor3 = CONFIG.Theme.TextDim
status.TextSize = 11
status.Font = Enum.Font.Gotham
status.TextXAlignment = Enum.TextXAlignment.Center
status.Parent = keyFrame

-- ===== HUB SCREEN =====
local hub = Instance.new("Frame")
hub.Size = UDim2.new(1, 0, 1, 0)
hub.BackgroundTransparency = 1
hub.Visible = false
hub.Parent = main

-- Header
local hdr = Instance.new("Frame")
hdr.Size = UDim2.new(1, 0, 0, 50)
hdr.BackgroundTransparency = 1
hdr.Parent = hub

local hdrIcon = Instance.new("Frame")
hdrIcon.Size = UDim2.new(0, 36, 0, 36)
hdrIcon.Position = UDim2.new(0, 16, 0, 7)
hdrIcon.BackgroundColor3 = CONFIG.Theme.Primary
hdrIcon.Parent = hdr

corner(hdrIcon, 10)

local hdrIconTxt = Instance.new("TextLabel")
hdrIconTxt.Size = UDim2.new(1, 0, 1, 0)
hdrIconTxt.BackgroundTransparency = 1
hdrIconTxt.Text = "🛡️"
hdrIconTxt.TextSize = 18
hdrIconTxt.Parent = hdrIcon

local hdrTitle = Instance.new("TextLabel")
hdrTitle.Size = UDim2.new(0, 200, 0, 22)
hdrTitle.Position = UDim2.new(0, 60, 0, 7)
hdrTitle.BackgroundTransparency = 1
hdrTitle.Text = "Script Hub"
hdrTitle.TextColor3 = CONFIG.Theme.Text
hdrTitle.TextSize = 16
hdrTitle.Font = Enum.Font.GothamBold
hdrTitle.TextXAlignment = Enum.TextXAlignment.Left
hdrTitle.Parent = hdr

local hdrSub = Instance.new("TextLabel")
hdrSub.Size = UDim2.new(0, 200, 0, 14)
hdrSub.Position = UDim2.new(0, 60, 0, 28)
hdrSub.BackgroundTransparency = 1
hdrSub.Text = "Sandbox Mode | " .. tostring(#GAMES) .. " Scripts"
hdrSub.TextColor3 = CONFIG.Theme.Success
hdrSub.TextSize = 10
hdrSub.Font = Enum.Font.Gotham
hdrSub.TextXAlignment = Enum.TextXAlignment.Left
hdrSub.Parent = hdr

local logout = Instance.new("TextButton")
logout.Size = UDim2.new(0, 70, 0, 28)
logout.Position = UDim2.new(1, -90, 0, 11)
logout.BackgroundColor3 = CONFIG.Theme.CardBackground
logout.BorderSizePixel = 0
logout.Text = "Logout"
logout.TextColor3 = CONFIG.Theme.TextDim
logout.TextSize = 11
logout.Font = Enum.Font.Gotham
logout.AutoButtonColor = false
logout.Parent = hdr

corner(logout, 8)
stroke(logout, CONFIG.Theme.Border, 1)

-- Scroll area for cards
local scroll = Instance.new("ScrollingFrame")
scroll.Size = UDim2.new(1, -32, 0, 220)
scroll.Position = UDim2.new(0, 16, 0, 55)
scroll.BackgroundTransparency = 1
scroll.BorderSizePixel = 0
scroll.ScrollBarThickness = 3
scroll.ScrollBarImageColor3 = CONFIG.Theme.Primary
scroll.Parent = hub

local grid = Instance.new("UIGridLayout")
grid.CellSize = UDim2.new(0, 220, 0, 100)
grid.CellPadding = UDim2.new(0, 10, 0, 10)
grid.SortOrder = Enum.SortOrder.LayoutOrder
grid.Parent = scroll

-- Console
local con = Instance.new("Frame")
con.Size = UDim2.new(1, -32, 0, 90)
con.Position = UDim2.new(0, 16, 1, -100)
con.BackgroundColor3 = CONFIG.Theme.CardBackground
con.BorderSizePixel = 0
con.Parent = hub

corner(con, 12)

local conTitle = Instance.new("TextLabel")
conTitle.Size = UDim2.new(1, -16, 0, 20)
conTitle.Position = UDim2.new(0, 8, 0, 4)
conTitle.BackgroundTransparency = 1
conTitle.Text = "Test Output"
conTitle.TextColor3 = CONFIG.Theme.Text
conTitle.TextSize = 11
conTitle.Font = Enum.Font.GothamBold
conTitle.TextXAlignment = Enum.TextXAlignment.Left
conTitle.Parent = con

local conText = Instance.new("TextLabel")
conText.Size = UDim2.new(1, -16, 1, -26)
conText.Position = UDim2.new(0, 8, 0, 24)
conText.BackgroundTransparency = 1
conText.Text = "[AUTH] Admin authenticated successfully\n[INFO] " .. tostring(#GAMES) .. " scripts auto-loaded\n[INFO] Sandbox environment initialized\n[READY] Waiting for test selection..."
conText.TextColor3 = CONFIG.Theme.TextDim
conText.TextSize = 10
conText.Font = Enum.Font.Code
conText.TextXAlignment = Enum.TextXAlignment.Left
conText.TextYAlignment = Enum.TextYAlignment.Top
conText.TextWrapped = true
conText.Parent = con

-- Hover helper
local function hover(btn, normal, hover)
    btn.MouseEnter:Connect(function()
        tween(btn, {BackgroundColor3 = hover}, 0.2)
    end)
    btn.MouseLeave:Connect(function()
        tween(btn, {BackgroundColor3 = normal}, 0.2)
    end)
end

hover(submit, CONFIG.Theme.Primary, Color3.fromRGB(167, 139, 250))
hover(logout, CONFIG.Theme.CardBackground, Color3.fromRGB(45, 45, 55))

-- Build cards
for i, game in ipairs(GAMES) do
    local card = Instance.new("Frame")
    card.Size = UDim2.new(0, 220, 0, 100)
    card.BackgroundColor3 = CONFIG.Theme.CardBackground
    card.BorderSizePixel = 0
    card.LayoutOrder = i
    card.Parent = scroll
    
    corner(card, 12)
    stroke(card, CONFIG.Theme.Border, 1)
    
    -- Color bar
    local bar = Instance.new("Frame")
    bar.Size = UDim2.new(1, 0, 0, 3)
    bar.BackgroundColor3 = game.color
    bar.BorderSizePixel = 0
    bar.Parent = card
    corner(bar, 4)
    
    -- Icon
    local img = Instance.new("ImageLabel")
    img.Size = UDim2.new(0, 32, 0, 32)
    img.Position = UDim2.new(0, 10, 0, 12)
    img.BackgroundColor3 = game.color
    img.BackgroundTransparency = 0.8
    img.BorderSizePixel = 0
    img.Image = game.icon
    img.Parent = card
    corner(img, 8)
    
    -- Name
    local name = Instance.new("TextLabel")
    name.Size = UDim2.new(1, -20, 0, 18)
    name.Position = UDim2.new(0, 10, 0, 48)
    name.BackgroundTransparency = 1
    name.Text = game.name
    name.TextColor3 = CONFIG.Theme.Text
    name.TextSize = 13
    name.Font = Enum.Font.GothamBold
    name.TextXAlignment = Enum.TextXAlignment.Left
    name.Parent = card
    
    -- Desc
    local desc = Instance.new("TextLabel")
    desc.Size = UDim2.new(1, -20, 0, 14)
    desc.Position = UDim2.new(0, 10, 0, 65)
    desc.BackgroundTransparency = 1
    desc.Text = game.description
    desc.TextColor3 = CONFIG.Theme.TextDim
    desc.TextSize = 10
    desc.Font = Enum.Font.Gotham
    desc.TextXAlignment = Enum.TextXAlignment.Left
    desc.Parent = card
    
    -- Run button
    local run = Instance.new("TextButton")
    run.Size = UDim2.new(1, -20, 0, 26)
    run.Position = UDim2.new(0, 10, 1, -36)
    run.BackgroundColor3 = game.color
    run.BackgroundTransparency = 0.2
    run.BorderSizePixel = 0
    run.Text = "Run Test"
    run.TextColor3 = CONFIG.Theme.Text
    run.TextSize = 11
    run.Font = Enum.Font.GothamBold
    run.AutoButtonColor = false
    run.Parent = card
    corner(run, 6)
    
    local hov = Color3.fromRGB(
        math.min(game.color.R * 255 + 30, 255),
        math.min(game.color.G * 255 + 30, 255),
        math.min(game.color.B * 255 + 30, 255)
    )
    hover(run, game.color, hov)
    
    -- Click handler
    run.MouseButton1Click:Connect(function()
        conText.Text = conText.Text .. "\n[RUNNING] " .. game.name .. "..."
        
        task.spawn(function()
            local ok, err = pcall(game.script)
            if ok then
                conText.Text = conText.Text .. "\n[OK] " .. game.name .. " done"
            else
                conText.Text = conText.Text .. "\n[ERR] " .. tostring(err)
            end
            conText.Text = conText.Text .. "\n[READY] Next?"
        end)
    end)
    
    -- Card hover
    card.MouseEnter:Connect(function()
        tween(card, {BackgroundColor3 = Color3.fromRGB(35, 35, 48)}, 0.2)
    end)
    card.MouseLeave:Connect(function()
        tween(card, {BackgroundColor3 = CONFIG.Theme.CardBackground}, 0.2)
    end)
end

-- Auto-size canvas
grid:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
    scroll.CanvasSize = UDim2.new(0, 0, 0, grid.AbsoluteContentSize.Y + 10)
end)
scroll.CanvasSize = UDim2.new(0, 0, 0, grid.AbsoluteContentSize.Y + 10)

-- ===== KEY HANDLING =====
local function validate(k)
    return k == CONFIG.AdminKey
end

submit.MouseButton1Click:Connect(function()
    if validate(keyBox.Text) then
        errLabel.Text = ""
        -- Simple switch - no complex fade
        keyFrame.Visible = false
        hub.Visible = true
        print("[Hub] Authenticated! Showing " .. tostring(#GAMES) .. " games.")
    else
        errLabel.Text = "Invalid key. Access denied."
        keyBox.BackgroundColor3 = Color3.fromRGB(60, 30, 30)
        tween(keyBox, {BackgroundColor3 = CONFIG.Theme.CardBackground}, 0.5)
    end
end)

logout.MouseButton1Click:Connect(function()
    hub.Visible = false
    keyFrame.Visible = true
    keyBox.Text = ""
end)

keyBox.FocusLost:Connect(function(enter)
    if enter then
        submit.MouseButton1Click:Fire()
    end
end)

-- Draggable
local drag, dragStart, startPos = false, nil, nil

main.InputBegan:Connect(function(inp)
    if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then
        drag = true
        dragStart = inp.Position
        startPos = main.Position
    end
end)

main.InputChanged:Connect(function(inp)
    if drag and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then
        local delta = inp.Position - dragStart
        main.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
    end
end)

main.InputEnded:Connect(function(inp)
    if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then
        drag = false
    end
end)

-- Intro pop
main.Size = UDim2.new(0, 0, 0, 0)
main.Position = UDim2.new(0.5, 0, 0.5, 0)
tween(main, {Size = UDim2.new(0, 500, 0, 400), Position = UDim2.new(0.5, -250, 0.5, -200)}, 0.5, Enum.EasingStyle.Back, Enum.EasingDirection.Out)

print("[Hub] Ready! Key: " .. CONFIG.AdminKey)
